
services:
  roach1:
    image: cockroachdb/cockroach:latest-v23.1
    container_name: roach1
    hostname: roach1
    command: start --insecure --join=roach1,roach2,roach3
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - roach1-data:/cockroach/cockroach-data
    networks:
      - roachnet

  roach2:
    image: cockroachdb/cockroach:latest-v23.1
    container_name: roach2
    hostname: roach2
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - roach2-data:/cockroach/cockroach-data
    networks:
      - roachnet

  roach3:
    image: cockroachdb/cockroach:latest-v23.1
    container_name: roach3
    hostname: roach3
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - roach3-data:/cockroach/cockroach-data
    networks:
      - roachnet

  roach4:
    image: cockroachdb/cockroach:latest-v23.1
    container_name: roach4
    hostname: roach4
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - roach4-data:/cockroach/cockroach-data
    networks:
      - roachnet

  roach5:
    image: cockroachdb/cockroach:latest-v23.1
    container_name: roach5
    hostname: roach5
    command: start --insecure --join=roach1,roach2,roach3
    volumes:
      - roach5-data:/cockroach/cockroach-data
    networks:
      - roachnet

volumes:
  roach1-data:
  roach2-data:
  roach3-data:
  roach4-data:
  roach5-data:

networks:
  roachnet:
    driver: bridge